USE mytest;
CREATE TABLE IF NOT EXISTS t_husband
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(100) CHARSET utf8 NULL,
  user_work VARCHAR(255) CHARSET utf8 NULL
);

DROP TABLE t_wife;
CREATE TABLE IF NOT EXISTS t_wife
(
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `husband_id` BIGINT,
  `age` INT(10) DEFAULT NULL,
  `name` VARCHAR(100) CHARSET utf8 NULL,
  `beauty` VARCHAR(100) CHARSET utf8 NULL
);

CREATE TABLE t_order
(
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT UNSIGNED,
  `number` INT(11) DEFAULT NULL, 
  `create_time` VARCHAR(20) CHARSET utf8 NULL
);

CREATE TABLE IF NOT EXISTS t_user
(
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `phone` VARCHAR(255) CHARSET utf8 NULL,
  `email` VARCHAR(255) CHARSET utf8 NULL,
  `vx_id` VARCHAR(255) CHARSET utf8 NULL,
  `vx_nickname` VARCHAR(255) CHARSET utf8 NULL,
  `user_password` VARCHAR(255) CHARSET utf8 NULL,
  `mark` VARCHAR(255) CHARSET utf8 NULL
);

DROP TABLE t_student;
CREATE TABLE IF NOT EXISTS t_student
(
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) CHARSET utf8 NULL,
  `age` INT(10) DEFAULT NULL,
  `level` VARCHAR(100) CHARSET utf8 NULL
);

CREATE TABLE IF NOT EXISTS t_teacher
(
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100),
  `age` INT(10),
  `dep` VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS t_stu_teach_rel
(
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `stu_id` BIGINT,
  `teach_id` BIGINT
)