package com.hust.lw.model;

public class HealthReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_female_health_report.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_female_health_report.employee_id
     *
     * @mbg.generated
     */
    private Long employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_female_health_report.liver
     *
     * @mbg.generated
     */
    private String liver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_female_health_report.heart
     *
     * @mbg.generated
     */
    private String heart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_male_health_report.id
     *
     * @return the value of t_male_health_report.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_male_health_report.id
     *
     * @param id the value for t_male_health_report.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_male_health_report.employee_id
     *
     * @return the value of t_male_health_report.employee_id
     *
     * @mbg.generated
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_male_health_report.employee_id
     *
     * @param employeeId the value for t_male_health_report.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_male_health_report.liver
     *
     * @return the value of t_male_health_report.liver
     *
     * @mbg.generated
     */
    public String getLiver() {
        return liver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_male_health_report.liver
     *
     * @param liver the value for t_male_health_report.liver
     *
     * @mbg.generated
     */
    public void setLiver(String liver) {
        this.liver = liver == null ? null : liver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_male_health_report.heart
     *
     * @return the value of t_male_health_report.heart
     *
     * @mbg.generated
     */
    public String getHeart() {
        return heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_male_health_report.heart
     *
     * @param heart the value for t_male_health_report.heart
     *
     * @mbg.generated
     */
    public void setHeart(String heart) {
        this.heart = heart == null ? null : heart.trim();
    }

}
