package com.hust.lw.model;

import java.util.ArrayList;
import java.util.List;

public class TFemaleHealthReportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public TFemaleHealthReportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNull() {
            addCriterion("employee_id is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNotNull() {
            addCriterion("employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdEqualTo(Long value) {
            addCriterion("employee_id =", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotEqualTo(Long value) {
            addCriterion("employee_id <>", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThan(Long value) {
            addCriterion("employee_id >", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("employee_id >=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThan(Long value) {
            addCriterion("employee_id <", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThanOrEqualTo(Long value) {
            addCriterion("employee_id <=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIn(List<Long> values) {
            addCriterion("employee_id in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotIn(List<Long> values) {
            addCriterion("employee_id not in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdBetween(Long value1, Long value2) {
            addCriterion("employee_id between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotBetween(Long value1, Long value2) {
            addCriterion("employee_id not between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andLiverIsNull() {
            addCriterion("liver is null");
            return (Criteria) this;
        }

        public Criteria andLiverIsNotNull() {
            addCriterion("liver is not null");
            return (Criteria) this;
        }

        public Criteria andLiverEqualTo(String value) {
            addCriterion("liver =", value, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverNotEqualTo(String value) {
            addCriterion("liver <>", value, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverGreaterThan(String value) {
            addCriterion("liver >", value, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverGreaterThanOrEqualTo(String value) {
            addCriterion("liver >=", value, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverLessThan(String value) {
            addCriterion("liver <", value, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverLessThanOrEqualTo(String value) {
            addCriterion("liver <=", value, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverLike(String value) {
            addCriterion("liver like", value, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverNotLike(String value) {
            addCriterion("liver not like", value, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverIn(List<String> values) {
            addCriterion("liver in", values, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverNotIn(List<String> values) {
            addCriterion("liver not in", values, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverBetween(String value1, String value2) {
            addCriterion("liver between", value1, value2, "liver");
            return (Criteria) this;
        }

        public Criteria andLiverNotBetween(String value1, String value2) {
            addCriterion("liver not between", value1, value2, "liver");
            return (Criteria) this;
        }

        public Criteria andHeartIsNull() {
            addCriterion("heart is null");
            return (Criteria) this;
        }

        public Criteria andHeartIsNotNull() {
            addCriterion("heart is not null");
            return (Criteria) this;
        }

        public Criteria andHeartEqualTo(String value) {
            addCriterion("heart =", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartNotEqualTo(String value) {
            addCriterion("heart <>", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartGreaterThan(String value) {
            addCriterion("heart >", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartGreaterThanOrEqualTo(String value) {
            addCriterion("heart >=", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartLessThan(String value) {
            addCriterion("heart <", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartLessThanOrEqualTo(String value) {
            addCriterion("heart <=", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartLike(String value) {
            addCriterion("heart like", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartNotLike(String value) {
            addCriterion("heart not like", value, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartIn(List<String> values) {
            addCriterion("heart in", values, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartNotIn(List<String> values) {
            addCriterion("heart not in", values, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartBetween(String value1, String value2) {
            addCriterion("heart between", value1, value2, "heart");
            return (Criteria) this;
        }

        public Criteria andHeartNotBetween(String value1, String value2) {
            addCriterion("heart not between", value1, value2, "heart");
            return (Criteria) this;
        }

        public Criteria andUterusIsNull() {
            addCriterion("uterus is null");
            return (Criteria) this;
        }

        public Criteria andUterusIsNotNull() {
            addCriterion("uterus is not null");
            return (Criteria) this;
        }

        public Criteria andUterusEqualTo(String value) {
            addCriterion("uterus =", value, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusNotEqualTo(String value) {
            addCriterion("uterus <>", value, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusGreaterThan(String value) {
            addCriterion("uterus >", value, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusGreaterThanOrEqualTo(String value) {
            addCriterion("uterus >=", value, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusLessThan(String value) {
            addCriterion("uterus <", value, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusLessThanOrEqualTo(String value) {
            addCriterion("uterus <=", value, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusLike(String value) {
            addCriterion("uterus like", value, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusNotLike(String value) {
            addCriterion("uterus not like", value, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusIn(List<String> values) {
            addCriterion("uterus in", values, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusNotIn(List<String> values) {
            addCriterion("uterus not in", values, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusBetween(String value1, String value2) {
            addCriterion("uterus between", value1, value2, "uterus");
            return (Criteria) this;
        }

        public Criteria andUterusNotBetween(String value1, String value2) {
            addCriterion("uterus not between", value1, value2, "uterus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_female_health_report
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_female_health_report
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}