package com.hust.lw.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_female_health_report
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TFemaleHealthReport extends HealthReport{
     /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_female_health_report.uterus
     *
     * @mbg.generated
     */
    private String uterus;


    public String getUterus() {
        return uterus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_female_health_report.uterus
     *
     * @param uterus the value for t_female_health_report.uterus
     *
     * @mbg.generated
     */
    public void setUterus(String uterus) {
        this.uterus = uterus == null ? null : uterus.trim();
    }
}