package com.hust.lw.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_male_health_report
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TMaleHealthReport extends HealthReport{
     /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_male_health_report.prostate
     *
     * @mbg.generated
     */
    private String prostate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_male_health_report.prostate
     *
     * @return the value of t_male_health_report.prostate
     *
     * @mbg.generated
     */
    public String getProstate() {
        return prostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_male_health_report.prostate
     *
     * @param prostate the value for t_male_health_report.prostate
     *
     * @mbg.generated
     */
    public void setProstate(String prostate) {
        this.prostate = prostate == null ? null : prostate.trim();
    }
}