server:
    port: 2525

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: dc3
        url: jdbc:mysql://127.0.0.1:3308/db0419?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai

mybatis-plus:
    mapper-locations: classpath:mapper/**.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl