USE mytest
CREATE TABLE IF NOT EXISTS t_person
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(100) CHARSET utf8 NULL,
  age INT(11) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS t_classmate
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  person_id BIGINT NOT NULL,
  school VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS t_workmate
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  person_id BIGINT NOT NULL,
  company VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS t_partner
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  person_id BIGINT NOT NULL,
  place VARCHAR(100)
);
SHOW TABLES;