package com.hust.lw.dao;

import com.hust.lw.model.TClassmate;
import com.hust.lw.model.TClassmateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TClassmateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    long countByExample(TClassmateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    int deleteByExample(TClassmateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    int insert(TClassmate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    int insertSelective(TClassmate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    List<TClassmate> selectByExample(TClassmateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    TClassmate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TClassmate record, @Param("example") TClassmateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TClassmate record, @Param("example") TClassmateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TClassmate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classmate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TClassmate record);

    List<TClassmate> selectByPersonId(Long id);
}