package com.hust.lw.dao;

import com.hust.lw.model.TPartner;
import com.hust.lw.model.TPartnerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    long countByExample(TPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    int deleteByExample(TPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    int insert(TPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    int insertSelective(TPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    List<TPartner> selectByExample(TPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    TPartner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPartner record, @Param("example") TPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPartner record, @Param("example") TPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPartner record);

    TPartner selectByPersonId(Long id);
}