server:
  port: 19087
spring:
  application:
    name: apigateway
  cloud:
    nacos:
      discovery:
        instance-enabled: true
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
    gateway:
      #http://127.0.0.1:18081/server/serverhello?content=liwei
      #http://127.0.0.1:19081/client/clienthello?content=lijing
      #===》
      #http://127.0.0.1:19087/abc/server/serverhello?content=liwei
      #http://127.0.0.1:19087/def/client/clienthello?content=lijing
      routes:                       # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
      - id: provider_route          # 当前路由的标识, 要求唯一
        uri: lb://provider  # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
        predicates:                # 断言(就是路由转发要满足的条件)
        - Path=/abc/**       # 当请求路径满足Path指定的规则时,才进行路由转发
        filters:                   # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
        - StripPrefix=1           # 转发之前去掉1层路径
      - id: consumer_route
        uri: lb://consumer-resttemplate
        predicates:
        - Path=/def/**
        filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
