package com.hust.lw.dao;

import com.hust.lw.model.TFemaleHealthReport;
import com.hust.lw.model.TMaleHealthReport;
import com.hust.lw.model.TMaleHealthReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMaleHealthReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    long countByExample(TMaleHealthReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    int deleteByExample(TMaleHealthReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    int insert(TMaleHealthReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    int insertSelective(TMaleHealthReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    List<TMaleHealthReport> selectByExample(TMaleHealthReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    TMaleHealthReport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMaleHealthReport record, @Param("example") TMaleHealthReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMaleHealthReport record, @Param("example") TMaleHealthReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMaleHealthReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_male_health_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMaleHealthReport record);

    TMaleHealthReport selectByEmployeeId(Long id);
}