package com.hust.lw.dao;

import com.hust.lw.model.THusband;
import com.hust.lw.model.THusbandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THusbandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    long countByExample(THusbandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    int deleteByExample(THusbandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    int insert(THusband record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    int insertSelective(THusband record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    List<THusband> selectByExample(THusbandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    THusband selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") THusband record, @Param("example") THusbandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") THusband record, @Param("example") THusbandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(THusband record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_husband
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(THusband record);
}