CREATE TABLE IF NOT EXISTS USER
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(255) CHARSET utf8 NULL,
  email VARCHAR(255) CHARSET utf8 NULL,
  vx_id VARCHAR(255) CHARSET utf8 NULL,
  vx_nickname VARCHAR(255) CHARSET utf8 NULL,
  PASSWORD VARCHAR(255) CHARSET utf8 NULL,
  mark VARCHAR(255) CHARSET utf8 NULL
);