CREATE TABLE IF NOT EXISTS USER
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  PASSWORD VARCHAR(255) NOT NULL,
  mark VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS message
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  command VARCHAR(255),
  description VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL
);