package com.hust.lw.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_classmate
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TClassmate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classmate.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classmate.person_id
     *
     * @mbg.generated
     */
    private Long personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classmate.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classmate.id
     *
     * @return the value of t_classmate.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classmate.id
     *
     * @param id the value for t_classmate.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classmate.person_id
     *
     * @return the value of t_classmate.person_id
     *
     * @mbg.generated
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classmate.person_id
     *
     * @param personId the value for t_classmate.person_id
     *
     * @mbg.generated
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classmate.school
     *
     * @return the value of t_classmate.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classmate.school
     *
     * @param school the value for t_classmate.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }
}