package com.hust.lw.model;

import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_person
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TPerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.age
     *
     * @mbg.generated
     */
    private Integer age;

    private TPartner partner;
    private List<TClassmate> classmateList;
    private List<TWorkmate> workmateList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.id
     *
     * @return the value of t_person.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.id
     *
     * @param id the value for t_person.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.user_name
     *
     * @return the value of t_person.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.user_name
     *
     * @param userName the value for t_person.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.age
     *
     * @return the value of t_person.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.age
     *
     * @param age the value for t_person.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    public void setPartner(TPartner partner) { this.partner = partner; }
    public void setClassmateList(List<TClassmate> classmateList) { this.classmateList = classmateList; }
    public void setWorkmateList(List<TWorkmate> workmateList) { this.workmateList = workmateList; }

    public TPartner getPartner() { return this.partner; }
    public List<TClassmate> getClassmateList() { return this.classmateList; }
    public List<TWorkmate> getWorkmateList() { return this.workmateList; }
}