package com.hust.lw.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_workmate
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TWorkmate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workmate.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workmate.person_id
     *
     * @mbg.generated
     */
    private Long personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workmate.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workmate.id
     *
     * @return the value of t_workmate.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workmate.id
     *
     * @param id the value for t_workmate.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workmate.person_id
     *
     * @return the value of t_workmate.person_id
     *
     * @mbg.generated
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workmate.person_id
     *
     * @param personId the value for t_workmate.person_id
     *
     * @mbg.generated
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workmate.company
     *
     * @return the value of t_workmate.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workmate.company
     *
     * @param company the value for t_workmate.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }
}