package com.hust.lw.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_husband
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class THusband {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_husband.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_husband.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_husband.user_work
     *
     * @mbg.generated
     */
    private String userWork;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_husband.id
     *
     * @return the value of t_husband.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_husband.id
     *
     * @param id the value for t_husband.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_husband.user_name
     *
     * @return the value of t_husband.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_husband.user_name
     *
     * @param userName the value for t_husband.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_husband.user_work
     *
     * @return the value of t_husband.user_work
     *
     * @mbg.generated
     */
    public String getUserWork() {
        return userWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_husband.user_work
     *
     * @param userWork the value for t_husband.user_work
     *
     * @mbg.generated
     */
    public void setUserWork(String userWork) {
        this.userWork = userWork == null ? null : userWork.trim();
    }

}