DROP TABLE CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER
(
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `userName` VARCHAR(50) DEFAULT NULL,
  `gender` INT(11) DEFAULT NULL, 
  `hobby` VARCHAR(255) DEFAULT NULL, 
  `member` INT(11) DEFAULT NULL, 
  `userAge` INT(11) DEFAULT NULL,
  `userAddress` VARCHAR(200) DEFAULT NULL,
  `reg_time` VARCHAR(200) DEFAULT NULL
);

DROP TABLE USER;
CREATE TABLE IF NOT EXISTS USER
(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(255) CHARSET utf8 NULL,
  email VARCHAR(255) CHARSET utf8 NULL,
  vx_id VARCHAR(255) CHARSET utf8 NULL,
  vx_nickname VARCHAR(255) CHARSET utf8 NULL,
  PASSWORD VARCHAR(255) CHARSET utf8 NULL,
  mark VARCHAR(255) CHARSET utf8 NULL
);