package com.hust.lw.dao;

import com.hust.lw.model.TWife;
import com.hust.lw.model.TWifeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TWifeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    long countByExample(TWifeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    int deleteByExample(TWifeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    int insert(TWife record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    int insertSelective(TWife record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    List<TWife> selectByExample(TWifeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    TWife selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TWife record, @Param("example") TWifeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TWife record, @Param("example") TWifeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TWife record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wife
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TWife record);

    TWife selectAll(Long id);

    TWife selectWifeByHusbandId(Long id);
}