package com.hust.lw.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_wife
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TWife {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wife.id
     *
     * @mbg.generated
     */
    private Long id;

    private Long husband_id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wife.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wife.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wife.beauty
     *
     * @mbg.generated
     */
    private String beauty;

    //private THusband husband;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wife.id
     *
     * @return the value of t_wife.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wife.id
     *
     * @param id the value for t_wife.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    public Long getHusband_id(){ return husband_id; }
    public void setHusband_id(Long husband_id){ this.husband_id = husband_id; }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wife.age
     *
     * @return the value of t_wife.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wife.age
     *
     * @param age the value for t_wife.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wife.name
     *
     * @return the value of t_wife.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wife.name
     *
     * @param name the value for t_wife.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wife.beauty
     *
     * @return the value of t_wife.beauty
     *
     * @mbg.generated
     */
    public String getBeauty() {
        return beauty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wife.beauty
     *
     * @param beauty the value for t_wife.beauty
     *
     * @mbg.generated
     */
    public void setBeauty(String beauty) {
        this.beauty = beauty == null ? null : beauty.trim();
    }

    //void setHusband(THusband husband){ this.husband = husband; }

    //THusband getHusband(){ return this.husband; }
}